version: '3'

services:

  loadbalancer:
    container_name: nginx_container
    image: nginx:latest
    restart: always
    expose:
      - 9999
    # ports:
    #   - 9999:9999
    network_mode: "host"
    volumes:
      - ./scripts/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ulimits:
      nofile:
        soft: "30000"
        hard: "50000"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: '0.5GB'

  app1:
    container_name: app1
    image: node:18.17
    working_dir: /code
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - APP_PORT=8081
    expose:
      - 8081
    network_mode: "host"
    command: npm run cluster
    volumes:
      - ./app:/code
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: '0.5GB'
  
  app2:
    container_name: app2
    image: node:18.17
    working_dir: /code
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - APP_PORT=8082
    expose:
      - 8082
    network_mode: "host"
    command: npm run cluster
    volumes:
      - ./app:/code
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: '0.5GB'

  redis:
    container_name: cache
    image: redis:7.0.10
    restart: always
    expose:
      - 6379
    network_mode: "host"
    volumes:
      - ./scripts/redis/:/etc/redis/
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.25'
    #       memory: '0.5GB'
  
  # database:
  #   container_name: mysql_container
  #   image: mysql:8.1.0
  #   command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_PASSWORD=root
  #     - MYSQL_DATABASE=backend
  #   volumes:
  #     - data:/var/lib/mysql
  #     - ./docker/mysql/my.cnf:/etc/my.cnf
  #     - ./docker/mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: '1GB'
    
  database:
    container_name: mariadb_container
    image: mariadb:11.1.2
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    expose:
      - 3306
    network_mode: "host"
    volumes:
      - data:/var/lib/mysql
      - ./scripts/mariadb/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
      - ./scripts/mariadb/schema.sql:/docker-entrypoint-initdb.d/1.sql
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1GB'
    
  
  # database:
  #   container_name: pgsql_container
  #   hostname: pgsql
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=backend
  #   command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
  #   expose:
  #     - 5432
  #   network_mode: "host"
  #   volumes:
  #     - data:/var/lib/postgresql/data
  #     - ./scripts/pgsql/postgresql-1.conf:/docker-entrypoint-initdb.d/postgresql.conf
  #     - ./scripts/pgsql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: '1GB'

volumes:
  data: